Added a runtime exception catch when creating a NetCDF file since I keep seeing:
java.lang.RuntimeException: NetCDF: Can't add HDF5 file metadata
	at gov.usgs.cida.netcdf.jna.NCUtil.status(NCUtil.java:32) ~[netcdf-jna-4.1.3-3.jar:na]
	at gov.usgs.cida.netcdf.dsg.StationTimeSeriesNetCDFFile.<init>(StationTimeSeriesNetCDFFile.java:64) ~[netcdf-dsg-1.3.jar:na]
	at gov.usgs.cida.watersmart.parse.CreateDSGFromZip.create(CreateDSGFromZip.java:121) ~[watersmart-parse-007-SNAPSHOT.jar:na]
	at gov.usgs.cida.watersmart.util.WPSTask.run(WPSImpl.java:355) ~[WPSTask.class:na]